### PR TITLE
Replaced all Sys::Statistics::Linux->new calls by native versions and add added support of statfile for all related functions.

### PR DESCRIPTION
**Pull request by kubashin-a**
Hello.

I want to update check_linux_stats.pl plugin in some parts.
I'm glad if it'll be usefull.

### CODE REVIEW

**Comment by rabner** [comment]
Hello kubashin-a, lazyfrosch,

I've just started my advenutre with icinga2 and want good plugin for linux. Changes kubashin made address (so far I've checked) io stats perfdata being displayed on OK status, but now it allways show CRITICAL no matter parameters setting. 

Any chance to continue with development of check_linux_stats.pl?

R.

**Comment by lazyfrosch** [comment]
I'm not really using the plugin anymore, but it is still here for archival reasons

**Comment by rabner** [comment]
Thanks for replay. I can see this plugin doesn't work consistently on different OS. Anyhow, I might need to look for something else. If I only had enough programming skills... BTW can you recommend basic plugin set for Linux stats?

**Comment by lazyfrosch** [comment]
Thanks for the request, this repository hasn't been maintained for years and will be archived

**Pull request closed without merging**
